name: Deploy Matebot
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        KEY: ${{ secrets.SSH_KEY }}
      with:
        source: "."
        target: "~/Bots/matebot"

    - name: Build the docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        KEY: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/Bots/matebot
          docker build -t matebot-image .
        
    - name: Stop the current container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        KEY: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/Bots/matebot
          docker run -d --restart always -e DISCORD_PREFIX=${{ secrets.DISCORD_PREFIX }} -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} -e FAUNADB_SECRET_KEY=${{ secrets.FAUNADB_SECRET_KEY }} --name matebot matebot-image
